data_manage/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views


app_name = 'data_manage'

urlpatterns = [
    path('data_manage/', views.data_manage_index, name='data_manage_index'),
    path('data_manage_show/', views.data_manage_show, name='data_manage_show'),
    path('', RedirectView.as_view(url='data_manage/')),
]

disaster/urls.py
from django.contrib import admin
from django.urls import include,path
from data_manage import views
from django.views.generic import RedirectView


urlpatterns = [
    path('disaster/', include('data_manage.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='disaster/')),
]

data_manage/models.py
from django.db import models

# Create your models here.
class Area(models.Model):
    code=models.CharField(primary_key=True,max_length=255,)
    name=models.CharField(max_length=255,)
class Data(models.Model):
    disaster_code=models.CharField(primary_key=True,max_length=255,)
    datetime=models.DateTimeField(blank=True, null=True)
    area = models.ForeignKey('Area', models.DO_NOTHING)
    village=models.CharField(max_length=255,)
    category=models.CharField(max_length=255,)
    basicallyIntactSquare=models.FloatField(blank=True, null=True)
    slightDamagedSquare=models.FloatField(blank=True, null=True)
    moderateDamagedSquare=models.FloatField(blank=True, null=True)
    seriousDamagedSquare=models.FloatField(blank=True, null=True)
    destroyedSquare=models.FloatField(blank=True, null=True)
    note=models.CharField(max_length=255,)
    reportingUnit=models.CharField(max_length=255,)

data_manage/views.py
from django.shortcuts import render
from django.http import Http404
from .models import Area,Data
from django.core.paginator import Paginator
import datetime

def data_manage_index(request):
    return render(request, "data_manage/data_manage.html")

def data_manage_show(request):
    area_name = request.GET.get('area_name')
    if len(area_name) == 0:
        return render(request, "data_manage/data_manage.html")
    start_time = request.GET.get('start_time')
    end_time = request.GET.get('end_time')
    try:
        area = Area.objects.get(name=area_name)
        data_all = area.data_set.all()
    except:
        data_all = []
    time_format = '%Y-%m-%d'
    if len(start_time) > 0  and len(end_time) > 0 \
            and datetime.datetime.strptime(start_time, time_format) \
            <= datetime.datetime.strptime(end_time, time_format):
        data_all = data_all.filter(datetime__lte=end_time, datetime__gte=start_time)
    
    paginator = Paginator(data_all, 30)      
    page_number = request.GET.get('page')
    data = paginator.get_page(page_number)
    
    context = {
        "area_name": area_name,
        "start_time": start_time,
        "end_time": end_time,
        "data": data,
    }
    return render(request, "data_manage/data_manage.html", context)

data_manage/templates/data_manage/data_manage.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body class="container">
    <h1 class="breadcrumb my-4><li class="breadcrumb-item active">灾情信息管理</h1>
    <form action="{% url 'data_manage:data_manage_show' %}" method="get">
        <p>
            选择地区：
            <input type="text" id="area_name" name="area_name" placeholder="输入地区名称" value={{ area_name }}>
        </p>
        
        <p>
            起止日期：
            <input type="date" name="start_time" value={{ start_time }}>
            <input type="date" name="end_time" value={{ end_time }}>
            <input type="submit" value="查询">
        </p>
    </form>    

    <p>
        评论列表：
        <table class="table table-bordered">
            <thead class="thead-inverse">
                <tr>
                    <th>时间</th>
                    <th>地点</th>
                    <th>种类</th>
                    <th>地震强度</th> 
                    <th>来源</th>
                </tr>
            </thead>           
            <tbody>
            {% for one in data %}
                <tr>
                    <td>{{ one.datetime }}</td>
                    <td>{{ one.area_id }}</td>
                    <td>{{ one.category }}</td>
                    <td>{{ one.note }}</td>
                    <td>{{ one.reportingUnit }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
            {% if data.has_previous %}
                <a href="?page=1&area_name={{ area_name }}&start_time={{ start_time }}&end_time={{ end_time }}" class="btn btn-info">&laquo; first</a>
                <a href="?page={{ data.previous_page_number }}&area_name={{ area_name }}&start_time={{ start_time }}&end_time={{ end_time }}" class="btn btn-primary">previous</a>
            {% endif %}

            <span class="current ">
                {% if data %}
                Page {{ data.number }} of {{ data.paginator.num_pages }}.
                {% endif %}
            </span>

            {% if data.has_next %}
                <a href="?page={{ data.next_page_number }}&area_name={{ area_name }}&start_time={{ start_time }}&end_time={{ end_time }}" class="btn btn-primary">next</a>
                <a href="?page={{ data.paginator.num_pages }}&area_name={{ area_name }}&start_time={{ start_time }}&end_time={{ end_time }}" class="btn btn-info">last &raquo;</a>
            {% endif %}
            </span>
        </div>
</body>
</html>